### PR TITLE
Added democracyclub_id

### PR DESCRIPTION
**Pull request by symroe**

### CODE REVIEW

**Comment by Floppy** [comment]
Yay! Are there more of these for things like individual constituency elections, or candidacies?

**Comment by symroe** [comment]
I think we're just going to be doing elections for now – with the GSS ID acting as the area ID (so, `ge2015-WMC-E14000615` or some such.).  What do you think?

(this is really a conversation for [the mailing list](https://groups.google.com/forum/#!topic/democracy-club/S6vwBS0jgGI)

**Comment by Floppy** [comment]
OK, interesting. Makes sense to use the standard geography IDs - at the moment I'm using mapit, but I think that's because of the Popolo docs (e.g. https://github.com/SomethingNewUK/election-data/blob/gh-pages/candidacies/2015-05-07-uk-general-election-horsham.json) 

And yes, I will follow the discussion on the list after Tim's post earlier on today.

**Comment by symroe** [comment]
I expect that's a better idea – I'm making this up on the hoof! ;)

**Pull request merged**
